# Ruff configuration for linting and formatting

# Target Python 3.11
target-version = "py311"

# Line length
line-length = 100

[lint]
# Enable pycodestyle (E, W), Pyflakes (F), isort (I), and more
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # Pyflakes
    "I",      # isort
    "N",      # pep8-naming
    "UP",     # pyupgrade
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "SIM",    # flake8-simplify
    "TCH",    # flake8-type-checking
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by formatter)
    "B008",   # Function call in default argument
]

# Allow autofix for all enabled rules
fixable = ["ALL"]
unfixable = []

# Exclude paths
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "*.egg-info",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
]

[lint.per-file-ignores]
# Test files can use fixtures as function arguments
"tests/**/*.py" = ["B008"]
# __init__.py files can have unused imports
"__init__.py" = ["F401"]

[lint.isort]
known-first-party = ["app"]
force-single-line = false
lines-after-imports = 2

[format]
# Use double quotes for strings
quote-style = "double"

# Use spaces instead of tabs
indent-style = "space"

# Automatically add trailing commas
skip-magic-trailing-comma = false

# Line ending style
line-ending = "auto"