services:
  postgres:
    image: postgres:16-alpine
    container_name: threads_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threads
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: threads_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8080:8080'
    command: start-dev
    healthcheck:
      test: ['CMD-SHELL', 'timeout 1 bash -c "</dev/tcp/localhost/8080" || exit 1']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: threads_ml_service
    restart: unless-stopped
    ports:
      - '8001:8000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/threads
      PYTHONUNBUFFERED: '1'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'python -c "import socket; socket.create_connection((''localhost'', 8000), timeout=2)" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./ml-service:/app
    networks:
      - default

volumes:
  postgres_data:
