services:
  postgres:
    image: postgres:16-alpine
    container_name: threads_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: threads
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: threads_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8080:8080'
    command: start-dev
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080/health/ready || exit 1']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

volumes:
  postgres_data:
