# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Threads - Next.js Social Media App

spec:
  description: A modern social media application built with Next.js, Prisma, and PostgreSQL
  icon: https://raw.githubusercontent.com/unknowntpo/threads-nextjs/master/public/icon.png
  tags:
    - nextjs
    - prisma
    - postgresql
    - social-media
    - nextauth

  variables: []

  readme: |
    # Threads - Social Media Application

    A modern social media platform built with Next.js 15, Prisma, PostgreSQL, and NextAuth v5.

    ## Features
    - 🔐 Authentication with NextAuth (Email, Google, GitHub)
    - 📝 Create and share posts
    - 🔄 Real-time feed updates
    - 💾 PostgreSQL database with Prisma ORM
    - 🎨 Modern UI with Tailwind CSS
    - ✅ Full E2E test coverage

    ## Post-Deployment Steps

    1. **Generate NextAuth Secret** (if not provided):
       ```bash
       openssl rand -base64 32
       ```

    2. **Configure OAuth Providers** (optional):
       - **Google**: Add redirect URI in Google Cloud Console
       - **GitHub**: Add redirect URI in GitHub OAuth App settings

    3. **Verify Deployment**:
       - Visit your app URL
       - Sign up for a new account
       - Create a test post

  services:
    - name: postgres
      template: PREBUILT
      spec:
        id: postgres
        source:
          image: postgres
        icon: https://cdn.zeabur.com/service-icons/postgresql.svg

    - name: app
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: unknowntpo/threads-nextjs
          branch: master
        ports:
          - id: web
            port: 3000
            type: HTTP
        env:
          DATABASE_URL:
            default: ${POSTGRES_URL}
          NODE_ENV:
            default: production
