# yaml-language-server: $schema=https://schema.zeabur.app/template.json
apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Threads - Next.js Social Media App

spec:
  description: A modern social media application built with Next.js 15, Prisma, PostgreSQL, and NextAuth v5
  icon: https://cdn.zeabur.com/service-icons/nextjs.svg
  tags:
    - nextjs
    - prisma
    - postgresql
    - social-media
    - nextauth
  variables: []
  readme: |
    # Threads - Social Media Application

    A modern social media platform built with Next.js 15, Prisma, PostgreSQL, and NextAuth v5.

    ## Features
    - 🔐 Authentication with NextAuth (Email, Google, GitHub)
    - 📝 Create and share posts
    - 🔄 Real-time feed updates
    - 💾 PostgreSQL database with Prisma ORM
    - 🎨 Modern UI with Tailwind CSS
    - ✅ Full E2E test coverage

    ## Post-Deployment Steps

    1. Configure environment variables via GitHub Actions secrets
    2. Set up OAuth providers (optional)
    3. Verify deployment and test functionality

  services:
    - name: app
      icon: https://service-icons.zeabur.com/git/docker/default.svg
      template: PREBUILT
      spec:
        source:
          image: ghcr.io/unknowntpo/threads-nextjs:latest
        ports:
          - id: web
            port: 3000
            type: HTTP
        env:
          DATABASE_URL:
            default: ${DATABASE_URL}
          NODE_ENV:
            default: production

    - name: migrations
      icon: https://service-icons.zeabur.com/git/docker/default.svg
      template: PREBUILT
      spec:
        source:
          image: ghcr.io/unknowntpo/threads-nextjs:latest
        command:
          - sh
          - -c
          - pnpm prisma migrate deploy
        restartPolicy: Never
        env:
          DATABASE_URL:
            default: postgresql://root:${POSTGRES_PASSWORD}@postgresql.zeabur.internal:5432/zeabur
