apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threads
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nextjs=us-east1-docker.pkg.dev/web-service-design/threads/nextjs:latest,ml-service=us-east1-docker.pkg.dev/web-service-design/threads/ml-service:latest
    argocd-image-updater.argoproj.io/nextjs.update-strategy: latest
    argocd-image-updater.argoproj.io/ml-service.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/unknowntpo/threads-nextjs.git
    targetRevision: master
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: threads

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
