name: Deploy to Zeabur

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual trigger

# Only allow one deployment at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=master-
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Zeabur
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: zeabur auth login --token $ZEABUR_TOKEN

      - name: Set Zeabur project context
        run: zeabur context set project --id ${{ secrets.ZEABUR_PROJECT_ID }} -y

      - name: Check if service exists and trigger provision if needed
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if service exists
          if zeabur service list 2>/dev/null | grep -q "app"; then
            echo "Service 'app' exists"
          else
            echo "Service 'app' not found, triggering provision workflow..."
            gh workflow run provision.yml -f project_id=${{ secrets.ZEABUR_PROJECT_ID }}
            echo "Waiting for provision to complete..."
            sleep 10
            # Wait for provision workflow to complete (timeout after 2 minutes)
            for i in {1..24}; do
              latest_run=$(gh run list --workflow=provision.yml --limit 1 --json status,conclusion --jq '.[0]')
              status=$(echo $latest_run | jq -r '.status')
              conclusion=$(echo $latest_run | jq -r '.conclusion')

              if [ "$status" = "completed" ]; then
                if [ "$conclusion" = "success" ]; then
                  echo "Provision completed successfully"
                  break
                else
                  echo "Provision failed with conclusion: $conclusion"
                  exit 1
                fi
              fi

              echo "Provision still running, waiting... ($i/24)"
              sleep 5
            done

            if [ "$status" != "completed" ]; then
              echo "Provision timed out after 2 minutes"
              exit 1
            fi
          fi

      - name: Deploy Docker Image to Zeabur
        run: zeabur service update tag --id ${{ secrets.ZEABUR_SERVICE_ID }} -t latest -y

      - name: Deployment Summary
        if: always()
        run: |
          echo "### Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ghcr.io/${{ github.repository }}:master-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Deployment failed! Check the logs above for details."
