name: Deploy to Zeabur

on:
  workflow_run:
    workflows: ['Docker Build and Push']
    types:
      - completed
    branches:
      - master
  workflow_dispatch: # Allow manual trigger

# Only allow one deployment at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-provision:
    name: Check if Provisioning Needed
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      statuses: write
    outputs:
      needs_provision: ${{ steps.check.outputs.needs_provision }}
    steps:
      - name: Set commit status to pending
        if: github.event_name == 'workflow_run'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
              state: 'pending',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Deploying to Zeabur...',
              context: 'Deploy to Zeabur'
            })

      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: zeabur auth login --token $ZEABUR_TOKEN

      - name: Set Zeabur project context
        run: zeabur context set project --id 682fe22e75f92a6870540c4f -y

      - name: Check if service exists
        id: check
        run: |
          if zeabur service list 2>/dev/null | grep -q "app"; then
            echo "Service 'app' exists"
            echo "needs_provision=false" >> $GITHUB_OUTPUT
          else
            echo "Service 'app' not found"
            echo "needs_provision=true" >> $GITHUB_OUTPUT
          fi

  provision:
    name: Provision Zeabur Services
    needs: check-provision
    if: needs.check-provision.outputs.needs_provision == 'true'
    uses: ./.github/workflows/provision.yml
    with:
      project_id: '682fe22e75f92a6870540c4f'
    secrets: inherit

  deploy:
    name: Deploy to Zeabur
    runs-on: ubuntu-latest
    needs: [check-provision, provision]
    if: always() && (needs.provision.result == 'success' || needs.provision.result == 'skipped')
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: zeabur auth login --token $ZEABUR_TOKEN --debug

      - name: Set Zeabur project context
        run: zeabur context set project --id 682fe22e75f92a6870540c4f -y

      - name: Deploy Docker Image to Zeabur
        run: zeabur service update tag --id ${{ secrets.ZEABUR_SERVICE_ID }} -t latest -y

      - name: Deployment Summary
        if: always()
        run: |
          echo "### Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ghcr.io/${{ github.repository }}:master-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY

      - name: Set commit status to success
        if: success() && github.event_name == 'workflow_run'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
              state: 'success',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Deployed successfully to Zeabur',
              context: 'Deploy to Zeabur'
            })

      - name: Set commit status to failure
        if: failure() && github.event_name == 'workflow_run'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ github.event.workflow_run.head_sha }}',
              state: 'failure',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: 'Deployment failed',
              context: 'Deploy to Zeabur'
            })

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Deployment failed! Check the logs above for details."
