name: Deploy to Zeabur

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual trigger

# Only allow one deployment at a time
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=master-
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  check-provision:
    name: Check if Provisioning Needed
    runs-on: ubuntu-latest
    needs: build-docker
    outputs:
      needs_provision: ${{ steps.check.outputs.needs_provision }}
    steps:
      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: zeabur auth login --token $ZEABUR_TOKEN

      - name: Set Zeabur project context
        run: zeabur context set project --id 682fe22e75f92a6870540c4f -y

      - name: Check if service exists
        id: check
        run: |
          if zeabur service list 2>/dev/null | grep -q "app"; then
            echo "Service 'app' exists"
            echo "needs_provision=false" >> $GITHUB_OUTPUT
          else
            echo "Service 'app' not found"
            echo "needs_provision=true" >> $GITHUB_OUTPUT
          fi

  provision:
    name: Provision Zeabur Services
    needs: check-provision
    if: needs.check-provision.outputs.needs_provision == 'true'
    uses: ./.github/workflows/provision.yml
    with:
      project_id: '682fe22e75f92a6870540c4f'
    secrets: inherit

  deploy:
    name: Deploy to Zeabur
    runs-on: ubuntu-latest
    needs: [build-docker, check-provision, provision]
    if: always() && needs.build-docker.result == 'success' && (needs.provision.result == 'success' || needs.provision.result == 'skipped')

    steps:
      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: zeabur auth login --token $ZEABUR_TOKEN --debug

      - name: Set Zeabur project context
        run: zeabur context set project --id 682fe22e75f92a6870540c4f -y

      - name: Deploy Docker Image to Zeabur
        run: zeabur service update tag --id ${{ secrets.ZEABUR_SERVICE_ID }} -t latest -y

      - name: Deployment Summary
        if: always()
        run: |
          echo "### Deployment Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ghcr.io/${{ github.repository }}:master-${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Deployed by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Deployment failed! Check the logs above for details."
