name: ML Service CI

on:
  push:
    branches:
      - master
    paths:
      - 'ml-service/**'
      - '.github/workflows/ml-service-ci.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'ml-service/**'
      - '.github/workflows/ml-service-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.4.11'

      - name: Install ml-service dependencies
        shell: bash
        run: |
          cd ml-service
          uv sync

      - name: Lint with Ruff
        shell: bash
        run: |
          cd ml-service
          uv run ruff check app/ tests/ scripts/

      - name: Format check with Ruff
        shell: bash
        run: |
          cd ml-service
          uv run ruff format --check app/ tests/ scripts/

      - name: Run tests with coverage
        shell: bash
        run: |
          cd ml-service
          uv run pytest tests/ -v --cov=app --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./ml-service/coverage.xml
          flags: ml-service
          fail_ci_if_error: false
