name: Provision Zeabur Services

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Zeabur Project ID'
        required: true
        default: '682fe22e75f92a6870540c4f'

jobs:
  provision:
    name: Provision Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: npx zeabur@latest auth login --token $ZEABUR_TOKEN

      - name: Get repository ID
        id: repo
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          REPO_ID=$(gh api repos/${{ github.repository }} --jq '.id')
          echo "id=$REPO_ID" >> $GITHUB_OUTPUT

      - name: Prepare template with repo ID
        run: |
          # Replace repo ID placeholder
          sed "s/GITHUB_REPO_ID/${{ steps.repo.outputs.id }}/g" zeabur.yaml > zeabur-deploy.yaml

          echo "Generated template:"
          cat zeabur-deploy.yaml

      - name: Set Zeabur project context
        run: npx zeabur@latest context set project --id ${{ inputs.project_id }} -y

      - name: Provision services from template
        run: npx zeabur@latest template deploy -f zeabur-deploy.yaml -i=false

      - name: Set environment variables for app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
        run: |
          zeabur variable create --name app \
            -k DATABASE_URL="$DATABASE_URL" \
            -k NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
            -k NEXTAUTH_URL="$NEXTAUTH_URL" \
            -k AUTH_TRUST_HOST="true" \
            -y

      - name: List provisioned services
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: |
          zeabur context set project --id=${{ inputs.project_id }} -y
          zeabur service list

      - name: Provisioning Summary
        run: |
          echo "### Provisioning Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Project ID**: ${{ inputs.project_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Template**: zeabur.yaml" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
