name: Provision Zeabur Services

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Zeabur Project ID'
        required: true
        default: '682fe22e75f92a6870540c4f'

jobs:
  provision:
    name: Provision Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zeabur CLI
        run: npm install -g @zeabur/cli

      - name: Authenticate with Zeabur
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: npx zeabur@latest auth login --token $ZEABUR_TOKEN

      - name: Set Zeabur project context
        run: npx zeabur@latest context set project --id ${{ inputs.project_id }} -y

      - name: Provision services from template
        run: npx zeabur@latest template deploy -f zeabur.yaml -i=false

      - name: Set environment variables for app
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          ALICE_PASSWORD: ${{ secrets.ALICE_PASSWORD }}
          BOB_PASSWORD: ${{ secrets.BOB_PASSWORD }}
        run: |
          zeabur variable create --name app \
            -k DATABASE_URL="$DATABASE_URL" \
            -k NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
            -k NEXTAUTH_URL="$NEXTAUTH_URL" \
            -k AUTH_SECRET="$NEXTAUTH_SECRET" \
            -k AUTH_TRUST_HOST="true" \
            -k NODE_ENV="production" \
            -k ALICE_PASSWORD="$ALICE_PASSWORD" \
            -k BOB_PASSWORD="$BOB_PASSWORD" \
            -y

      - name: List provisioned services
        env:
          ZEABUR_TOKEN: ${{ secrets.ZEABUR_TOKEN }}
        run: |
          zeabur context set project --id=${{ inputs.project_id }} -y
          zeabur service list

      - name: Provisioning Summary
        run: |
          echo "### Provisioning Summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Project ID**: ${{ inputs.project_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Template**: zeabur.yaml" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
